---
# Per environment values which override defaults in hmpps-breach-notice-ui/values.yaml

generic-service:
  ingress:
    host: breach-notice.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://breach-notice.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api.prison.service.justice.gov.uk"
    AUDIT_ENABLED: "false"

generic-prometheus-alerts:
  alertSeverity: PROD_ALERTS_SEVERITY_LABEL
