name: Security veracode pipeline scan
on:
  workflow_dispatch:
  schedule:
    - cron: "19 6 * * MON-FRI" # Every weekday
jobs:
  security-veracode-pipeline-scan:
    name: Project security veracode pipeline scan
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/security_veracode_pipeline_scan.yml@b7e29ba10659e877df6b75f95fd3d18ae37212a8 # v2.19.1
    with:
      channel_id: breach-notice-notifications
    secrets: inherit
