name: Security veracode policy scan
on:
  workflow_dispatch:
  schedule:
    - cron: "34 6 * * 1" # Every Monday
jobs:
  security-veracode-policy-check:
    name: Project security veracode policy scan
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/security_veracode_policy_scan.yml@170627bc8c907cd068085c053acca71c74ce808e # v2.22.4
    with:
      channel_id: breach-notice-notifications
    secrets: inherit
