name: Security veracode pipeline scan
on:
  workflow_dispatch:
  schedule:
    - cron: "19 6 * * MON-FRI" # Every weekday
jobs:
  security-veracode-pipeline-scan:
    name: Project security veracode pipeline scan
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/security_veracode_pipeline_scan.yml@1b3b938084ba0e0803b045918aca69b8fb45c668 # v2.16.2
    with:
      channel_id: breach-notice-notifications
    secrets: inherit
