name: Security veracode policy scan
on:
  workflow_dispatch:
  schedule:
    - cron: "34 6 * * 1" # Every Monday
jobs:
  security-veracode-policy-check:
    name: Project security veracode policy scan
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/security_veracode_policy_scan.yml@3d0db04bde36486d182b5c7d4a3bb8794bdeb2c6 # v2.18.0
    with:
      channel_id: breach-notice-notifications
    secrets: inherit
