name: Security veracode pipeline scan
on:
  workflow_dispatch:
  schedule:
    - cron: "19 6 * * MON-FRI" # Every weekday
jobs:
  security-veracode-pipeline-scan:
    name: Project security veracode pipeline scan
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/security_veracode_pipeline_scan.yml@a731b6134c799eb068c00886f87aab0ae2a6efa6 # v2.14.7
    with:
      channel_id: breach-notice-notifications
    secrets: inherit
