name: Security veracode policy scan
on:
  workflow_dispatch:
  schedule:
    - cron: "34 6 * * 1" # Every Monday
jobs:
  security-veracode-policy-check:
    name: Project security veracode policy scan
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/security_veracode_policy_scan.yml@7b95e1e3569a5a612d19015d33d9ce572714be31 # v2.21.0
    with:
      channel_id: breach-notice-notifications
    secrets: inherit
